### ISSUE TITLE
Implement "actions" as a sequence

### ISSUE THREAD

**Issue by adrianhopebailie** [chromium/ballista#19]
It seems that using an object, where the attribute names are the action verbs, as opposed to a sequence of action objects will be quite difficult to model in WebIDL if you need to do this eventually.

Could you implement the actions property like so:

``` javascript
{
  "name": "WebEditor",
  "short_name": "Editor",
  "icons": [...],
  "actions": [{
    "verb" : "open",                        
    "bidirectional": true,
    "types": ["text/*"]
  }]
}            
```

**Comment by mgiuca** [comment]
Hi Adrian,

I missed this bug report before (sorry), but in the mean time, we did update the explainer / spec to do it this way for that same reason.
